<?php

namespace Database\Seeders;

use App\Models\AdmissionCandidate;
use Illuminate\Database\Seeder;

class AdmissionCandidateSeeder extends Seeder
{
    public function run(): void
    {
        $candidates = [
            [
                'admission_code'    => '01_TT_XTS_GBTT_00319',
                'expected_student_code' => null,
                'full_name'         => 'Nguyễn Văn An',
                'date_of_birth'     => '2006-03-15',
                'gender'            => 'male',
                'cccd'              => '052306001001',
                'phone'             => '0901234561',
                'email'             => 'annv06@gmail.com',
                'permanent_address' => 'Thôn 3, Xã Bình Thạnh, Huyện Bình Sơn, Quảng Ngãi',
                'major_code'        => 'CNTT',
                'major_name'        => 'Công nghệ thông tin',
                'course_year'       => '2026-2030',
                'school_year'       => '2026-2027',
                'status'            => 'admitted',
            ],
            [
                'admission_code'    => '01_TT_XTS_GBTT_00427',
                'expected_student_code' => null,
                'full_name'         => 'Trần Thị Bích',
                'date_of_birth'     => '2006-07-22',
                'gender'            => 'female',
                'cccd'              => '079306002002',
                'phone'             => '0912345672',
                'email'             => 'bichtt06@gmail.com',
                'permanent_address' => 'Số 12, Đường Lê Lợi, Phường 2, TP. Vũng Tàu, Bà Rịa - Vũng Tàu',
                'major_code'        => 'CK',
                'major_name'        => 'Cơ khí',
                'course_year'       => '2026-2030',
                'school_year'       => '2026-2027',
                'status'            => 'admitted',
            ],
            [
                'admission_code'    => '01_TT_XTS_GBTT_00583',
                'expected_student_code' => null,
                'full_name'         => 'Lê Minh Châu',
                'date_of_birth'     => '2006-11-08',
                'gender'            => 'male',
                'cccd'              => '048306003003',
                'phone'             => '0923456783',
                'email'             => 'chaulm06@gmail.com',
                'permanent_address' => 'Ấp Bình Đông, Xã Bình Phú, Huyện Châu Phú, An Giang',
                'major_code'        => 'QTKD',
                'major_name'        => 'Quản trị kinh doanh',
                'course_year'       => '2026-2030',
                'school_year'       => '2026-2027',
                'status'            => 'admitted',
            ],
            [
                'admission_code'    => '01_TT_XTS_GBTT_00701',
                'expected_student_code' => null,
                'full_name'         => 'Phạm Thị Diễm',
                'date_of_birth'     => '2006-05-30',
                'gender'            => 'female',
                'cccd'              => '092306004004',
                'phone'             => '0934567894',
                'email'             => 'diempt06@gmail.com',
                'permanent_address' => 'Xóm 7, Xã Tân Phú Đông, Huyện Sa Đéc, Đồng Tháp',
                'major_code'        => 'CNTP',
                'major_name'        => 'Công nghệ thực phẩm',
                'course_year'       => '2026-2030',
                'school_year'       => '2026-2027',
                'status'            => 'admitted',
            ],
            [
                'admission_code'    => '01_TT_XTS_GBTT_00812',
                'expected_student_code' => null,
                'full_name'         => 'Hoàng Văn Em',
                'date_of_birth'     => '2006-01-17',
                'gender'            => 'male',
                'cccd'              => '001306005005',
                'phone'             => '0945678905',
                'email'             => 'emhv06@gmail.com',
                'permanent_address' => '45 Ngõ 12, Đường Hoàng Văn Thụ, Phường Láng Hạ, Quận Đống Đa, Hà Nội',
                'major_code'        => 'XD',
                'major_name'        => 'Xây dựng dân dụng và công nghiệp',
                'course_year'       => '2026-2030',
                'school_year'       => '2026-2027',
                'status'            => 'admitted',
            ],
        ];

        foreach ($candidates as $data) {
            // Nếu candidate này đã thực sự nhập học (status=enrolled, có student_id) thì
            // không ghi đè status/student_id/enrolled_at — seed lại chỉ để cập nhật các
            // field tĩnh (email, địa chỉ...), tránh biến 1 candidate đã enrolled thật
            // trở lại 'admitted' một cách sai lệch (dữ liệu không khớp student_id còn đó).
            $existing = AdmissionCandidate::where('admission_code', $data['admission_code'])->first();
            if ($existing && $existing->status === 'enrolled') {
                unset($data['status'], $data['expected_student_code']);
            }

            AdmissionCandidate::updateOrCreate(
                ['admission_code' => $data['admission_code']],
                $data
            );
        }

        // 50 candidate nhập học thật, suy ra từ file Excel import demo
        // storage/imports/danh_sach_50_sinh_vien_nhap_hoc_v2.xlsx — dùng để test
        // bulkEnroll() với dữ liệu lớn hơn 5 candidate ban đầu. admission_code lấy
        // đúng 5 số cuối của student_code tương ứng trong Excel (đúng công thức gốc
        // "5 số cuối mã trúng tuyển = 5 số cuối MSSV"). email ở đây là email cá nhân
        // của hồ sơ trúng tuyển, không phải email trường sau nhập học.
        $importedCandidates = [
            [
                'admission_code'         => '01_TT_XTS_GBTT_90001',
                'expected_student_code'  => null,
                'full_name'              => 'Nguyễn Đức Hùng',
                'date_of_birth'          => '2008-12-04',
                'gender'                 => 'male',
                'cccd'                   => '087095424170',
                'phone'                  => '0914265799',
                'email'                  => 'hungnd08@gmail.com',
                'permanent_address'      => 'Số 130, Khánh Hòa',
                'major_code'             => 'DDT',
                'major_name'             => 'Điện - Điện tử',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90002',
                'expected_student_code'  => null,
                'full_name'              => 'Ngô Minh Phong',
                'date_of_birth'          => '2008-03-07',
                'gender'                 => 'male',
                'cccd'                   => '044014983820',
                'phone'                  => '0922981052',
                'email'                  => 'phongnm08@gmail.com',
                'permanent_address'      => 'Số 12, Lâm Đồng',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90003',
                'expected_student_code'  => null,
                'full_name'              => 'Nguyễn Quang Long',
                'date_of_birth'          => '2008-04-28',
                'gender'                 => 'male',
                'cccd'                   => '013145754350',
                'phone'                  => '0995320121',
                'email'                  => 'longnq08@gmail.com',
                'permanent_address'      => 'Số 54, Kiên Giang',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90004',
                'expected_student_code'  => null,
                'full_name'              => 'Hoàng Khánh Lan',
                'date_of_birth'          => '2008-01-08',
                'gender'                 => 'female',
                'cccd'                   => '005163807460',
                'phone'                  => '0918883684',
                'email'                  => 'lanhk08@gmail.com',
                'permanent_address'      => 'Số 55, Tây Ninh',
                'major_code'             => 'XD',
                'major_name'             => 'Xây dựng',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90005',
                'expected_student_code'  => null,
                'full_name'              => 'Lý Mỹ Nhi',
                'date_of_birth'          => '2008-03-17',
                'gender'                 => 'female',
                'cccd'                   => '064002149750',
                'phone'                  => '0930514014',
                'email'                  => 'nhilm08@gmail.com',
                'permanent_address'      => 'Số 153, Tiền Giang',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90006',
                'expected_student_code'  => null,
                'full_name'              => 'Ngô Diệu Giang',
                'date_of_birth'          => '2008-03-15',
                'gender'                 => 'female',
                'cccd'                   => '001188989750',
                'phone'                  => '0933978249',
                'email'                  => 'giangnd08@gmail.com',
                'permanent_address'      => 'Số 164, Bình Dương',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90007',
                'expected_student_code'  => null,
                'full_name'              => 'Trần Anh Long',
                'date_of_birth'          => '2008-04-19',
                'gender'                 => 'male',
                'cccd'                   => '011079556620',
                'phone'                  => '0919289546',
                'email'                  => 'longta08@gmail.com',
                'permanent_address'      => 'Số 141, Cà Mau',
                'major_code'             => 'DDT',
                'major_name'             => 'Điện - Điện tử',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90008',
                'expected_student_code'  => null,
                'full_name'              => 'Vũ Khánh Phương',
                'date_of_birth'          => '2008-04-03',
                'gender'                 => 'female',
                'cccd'                   => '044096808280',
                'phone'                  => '0940885476',
                'email'                  => 'phuongvk08@gmail.com',
                'permanent_address'      => 'Số 182, An Giang',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90009',
                'expected_student_code'  => null,
                'full_name'              => 'Đỗ Tuấn Tiến',
                'date_of_birth'          => '2008-08-26',
                'gender'                 => 'male',
                'cccd'                   => '053012016390',
                'phone'                  => '0998447167',
                'email'                  => 'tiendt08@gmail.com',
                'permanent_address'      => 'Số 120, Tiền Giang',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90010',
                'expected_student_code'  => null,
                'full_name'              => 'Võ Thành Duy',
                'date_of_birth'          => '2008-05-15',
                'gender'                 => 'male',
                'cccd'                   => '032079472720',
                'phone'                  => '0983863413',
                'email'                  => 'duyvt08@gmail.com',
                'permanent_address'      => 'Số 4, Gia Lai',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90011',
                'expected_student_code'  => null,
                'full_name'              => 'Hoàng Bảo Mai',
                'date_of_birth'          => '2008-12-26',
                'gender'                 => 'female',
                'cccd'                   => '072122991220',
                'phone'                  => '0949823450',
                'email'                  => 'maihb08@gmail.com',
                'permanent_address'      => 'Số 16, Gia Lai',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90012',
                'expected_student_code'  => null,
                'full_name'              => 'Dương Minh Cường',
                'date_of_birth'          => '2008-11-28',
                'gender'                 => 'male',
                'cccd'                   => '031116973470',
                'phone'                  => '0943046464',
                'email'                  => 'cuongdm08@gmail.com',
                'permanent_address'      => 'Số 21, Đà Nẵng',
                'major_code'             => 'QT',
                'major_name'             => 'Kinh tế - Quản trị',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90013',
                'expected_student_code'  => null,
                'full_name'              => 'Vũ Diệu Diễm',
                'date_of_birth'          => '2008-10-19',
                'gender'                 => 'female',
                'cccd'                   => '013083235080',
                'phone'                  => '0977898694',
                'email'                  => 'diemvd08@gmail.com',
                'permanent_address'      => 'Số 63, An Giang',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90014',
                'expected_student_code'  => null,
                'full_name'              => 'Lý Ngọc Hà',
                'date_of_birth'          => '2008-02-24',
                'gender'                 => 'female',
                'cccd'                   => '071043954420',
                'phone'                  => '0991178885',
                'email'                  => 'haln08@gmail.com',
                'permanent_address'      => 'Số 176, Cần Thơ',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90015',
                'expected_student_code'  => null,
                'full_name'              => 'Ngô Thanh Vy',
                'date_of_birth'          => '2008-12-15',
                'gender'                 => 'female',
                'cccd'                   => '071181101390',
                'phone'                  => '0925015458',
                'email'                  => 'vynt08@gmail.com',
                'permanent_address'      => 'Số 10, Gia Lai',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90016',
                'expected_student_code'  => null,
                'full_name'              => 'Bùi Quang Vinh',
                'date_of_birth'          => '2008-09-28',
                'gender'                 => 'male',
                'cccd'                   => '053032703950',
                'phone'                  => '0933763566',
                'email'                  => 'vinhbq08@gmail.com',
                'permanent_address'      => 'Số 106, Tây Ninh',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90017',
                'expected_student_code'  => null,
                'full_name'              => 'Huỳnh Thu Lan',
                'date_of_birth'          => '2008-11-07',
                'gender'                 => 'female',
                'cccd'                   => '052141727920',
                'phone'                  => '0947463522',
                'email'                  => 'lanht08@gmail.com',
                'permanent_address'      => 'Số 174, Long An',
                'major_code'             => 'DDT',
                'major_name'             => 'Điện - Điện tử',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90018',
                'expected_student_code'  => null,
                'full_name'              => 'Đỗ Diệu Oanh',
                'date_of_birth'          => '2008-02-13',
                'gender'                 => 'female',
                'cccd'                   => '074041465420',
                'phone'                  => '0968526649',
                'email'                  => 'oanhdd08@gmail.com',
                'permanent_address'      => 'Số 176, Gia Lai',
                'major_code'             => 'QT',
                'major_name'             => 'Kinh tế - Quản trị',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90019',
                'expected_student_code'  => null,
                'full_name'              => 'Võ Thu Yến',
                'date_of_birth'          => '2008-07-23',
                'gender'                 => 'female',
                'cccd'                   => '038035408690',
                'phone'                  => '0999245317',
                'email'                  => 'yenvt08@gmail.com',
                'permanent_address'      => 'Số 158, Đồng Nai',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90020',
                'expected_student_code'  => null,
                'full_name'              => 'Vũ Bảo Phương',
                'date_of_birth'          => '2008-09-16',
                'gender'                 => 'female',
                'cccd'                   => '095013975710',
                'phone'                  => '0979182797',
                'email'                  => 'phuongvb08@gmail.com',
                'permanent_address'      => 'Số 24, Tây Ninh',
                'major_code'             => 'XD',
                'major_name'             => 'Xây dựng',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90021',
                'expected_student_code'  => null,
                'full_name'              => 'Vũ Xuân Việt',
                'date_of_birth'          => '2008-12-23',
                'gender'                 => 'male',
                'cccd'                   => '050163558360',
                'phone'                  => '0929806690',
                'email'                  => 'vietvx08@gmail.com',
                'permanent_address'      => 'Số 200, Đồng Tháp',
                'major_code'             => 'QT',
                'major_name'             => 'Kinh tế - Quản trị',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90022',
                'expected_student_code'  => null,
                'full_name'              => 'Ngô Bảo Uyên',
                'date_of_birth'          => '2008-09-14',
                'gender'                 => 'female',
                'cccd'                   => '071128797790',
                'phone'                  => '0973709724',
                'email'                  => 'uyennb08@gmail.com',
                'permanent_address'      => 'Số 164, Khánh Hòa',
                'major_code'             => 'TK',
                'major_name'             => 'Thiết kế',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90023',
                'expected_student_code'  => null,
                'full_name'              => 'Lê Minh Hùng',
                'date_of_birth'          => '2008-03-23',
                'gender'                 => 'male',
                'cccd'                   => '028065273980',
                'phone'                  => '0954410148',
                'email'                  => 'hunglm08@gmail.com',
                'permanent_address'      => 'Số 53, Bà Rịa - Vũng Tàu',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90024',
                'expected_student_code'  => null,
                'full_name'              => 'Hoàng Hồng Oanh',
                'date_of_birth'          => '2008-12-18',
                'gender'                 => 'female',
                'cccd'                   => '078073300800',
                'phone'                  => '0946632757',
                'email'                  => 'oanhhh08@gmail.com',
                'permanent_address'      => 'Số 87, Long An',
                'major_code'             => 'QT',
                'major_name'             => 'Kinh tế - Quản trị',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90025',
                'expected_student_code'  => null,
                'full_name'              => 'Trần Xuân Duy',
                'date_of_birth'          => '2008-03-02',
                'gender'                 => 'male',
                'cccd'                   => '034153219410',
                'phone'                  => '0971028710',
                'email'                  => 'duytx08@gmail.com',
                'permanent_address'      => 'Số 72, Long An',
                'major_code'             => 'TK',
                'major_name'             => 'Thiết kế',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90026',
                'expected_student_code'  => null,
                'full_name'              => 'Ngô Văn Hùng',
                'date_of_birth'          => '2008-01-20',
                'gender'                 => 'male',
                'cccd'                   => '020025965640',
                'phone'                  => '0999853245',
                'email'                  => 'hungnv08@gmail.com',
                'permanent_address'      => 'Số 180, Bến Tre',
                'major_code'             => 'DDT',
                'major_name'             => 'Điện - Điện tử',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90027',
                'expected_student_code'  => null,
                'full_name'              => 'Đặng Hồng Nhi',
                'date_of_birth'          => '2008-02-19',
                'gender'                 => 'female',
                'cccd'                   => '089018310590',
                'phone'                  => '0950477742',
                'email'                  => 'nhidh08@gmail.com',
                'permanent_address'      => 'Số 145, Đồng Tháp',
                'major_code'             => 'XD',
                'major_name'             => 'Xây dựng',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90028',
                'expected_student_code'  => null,
                'full_name'              => 'Dương Bảo Giang',
                'date_of_birth'          => '2008-11-27',
                'gender'                 => 'female',
                'cccd'                   => '059062846920',
                'phone'                  => '0980027662',
                'email'                  => 'giangdb08@gmail.com',
                'permanent_address'      => 'Số 199, Gia Lai',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90029',
                'expected_student_code'  => null,
                'full_name'              => 'Đặng Mỹ Yến',
                'date_of_birth'          => '2008-01-16',
                'gender'                 => 'female',
                'cccd'                   => '042073224230',
                'phone'                  => '0957623800',
                'email'                  => 'yendm08@gmail.com',
                'permanent_address'      => 'Số 180, Đà Nẵng',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90030',
                'expected_student_code'  => null,
                'full_name'              => 'Bùi Bảo Phương',
                'date_of_birth'          => '2008-02-10',
                'gender'                 => 'female',
                'cccd'                   => '029134210800',
                'phone'                  => '0999115205',
                'email'                  => 'phuongbb08@gmail.com',
                'permanent_address'      => 'Số 136, Gia Lai',
                'major_code'             => 'TK',
                'major_name'             => 'Thiết kế',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90031',
                'expected_student_code'  => null,
                'full_name'              => 'Huỳnh Hữu Thắng',
                'date_of_birth'          => '2008-03-07',
                'gender'                 => 'male',
                'cccd'                   => '028148597820',
                'phone'                  => '0989133014',
                'email'                  => 'thanghh08@gmail.com',
                'permanent_address'      => 'Số 50, Đồng Tháp',
                'major_code'             => 'TK',
                'major_name'             => 'Thiết kế',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90032',
                'expected_student_code'  => null,
                'full_name'              => 'Đỗ Thanh Vy',
                'date_of_birth'          => '2008-08-04',
                'gender'                 => 'female',
                'cccd'                   => '002176019680',
                'phone'                  => '0969118721',
                'email'                  => 'vydt08@gmail.com',
                'permanent_address'      => 'Số 123, Lâm Đồng',
                'major_code'             => 'TK',
                'major_name'             => 'Thiết kế',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90033',
                'expected_student_code'  => null,
                'full_name'              => 'Trần Kim Giang',
                'date_of_birth'          => '2008-07-20',
                'gender'                 => 'female',
                'cccd'                   => '077084988550',
                'phone'                  => '0970467027',
                'email'                  => 'giangtk08@gmail.com',
                'permanent_address'      => 'Số 110, Huế',
                'major_code'             => 'QT',
                'major_name'             => 'Kinh tế - Quản trị',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90034',
                'expected_student_code'  => null,
                'full_name'              => 'Phạm Minh Thắng',
                'date_of_birth'          => '2008-01-14',
                'gender'                 => 'male',
                'cccd'                   => '058141342250',
                'phone'                  => '0941068214',
                'email'                  => 'thangpm08@gmail.com',
                'permanent_address'      => 'Số 19, Bến Tre',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90035',
                'expected_student_code'  => null,
                'full_name'              => 'Lý Đức Duy',
                'date_of_birth'          => '2008-03-26',
                'gender'                 => 'male',
                'cccd'                   => '040172303940',
                'phone'                  => '0972907576',
                'email'                  => 'duyld08@gmail.com',
                'permanent_address'      => 'Số 70, Long An',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90036',
                'expected_student_code'  => null,
                'full_name'              => 'Trần Quang Vinh',
                'date_of_birth'          => '2008-10-19',
                'gender'                 => 'male',
                'cccd'                   => '003191421850',
                'phone'                  => '0933513701',
                'email'                  => 'vinhtq08@gmail.com',
                'permanent_address'      => 'Số 72, Bến Tre',
                'major_code'             => 'TK',
                'major_name'             => 'Thiết kế',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90037',
                'expected_student_code'  => null,
                'full_name'              => 'Dương Minh Minh',
                'date_of_birth'          => '2008-08-10',
                'gender'                 => 'male',
                'cccd'                   => '085181384790',
                'phone'                  => '0971045700',
                'email'                  => 'minhd08@gmail.com',
                'permanent_address'      => 'Số 30, Tây Ninh',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90038',
                'expected_student_code'  => null,
                'full_name'              => 'Đặng Bảo Vy',
                'date_of_birth'          => '2008-01-07',
                'gender'                 => 'female',
                'cccd'                   => '035045593980',
                'phone'                  => '0975056916',
                'email'                  => 'vydb08@gmail.com',
                'permanent_address'      => 'Số 62, Đà Nẵng',
                'major_code'             => 'CNTP',
                'major_name'             => 'Công nghệ thực phẩm',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90039',
                'expected_student_code'  => null,
                'full_name'              => 'Bùi Minh Sơn',
                'date_of_birth'          => '2008-09-23',
                'gender'                 => 'male',
                'cccd'                   => '035175951580',
                'phone'                  => '0942713008',
                'email'                  => 'sonbm08@gmail.com',
                'permanent_address'      => 'Số 49, Long An',
                'major_code'             => 'XD',
                'major_name'             => 'Xây dựng',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90040',
                'expected_student_code'  => null,
                'full_name'              => 'Hoàng Đức Tiến',
                'date_of_birth'          => '2008-08-28',
                'gender'                 => 'male',
                'cccd'                   => '020186078680',
                'phone'                  => '0956321751',
                'email'                  => 'tienhd08@gmail.com',
                'permanent_address'      => 'Số 97, Gia Lai',
                'major_code'             => 'QT',
                'major_name'             => 'Kinh tế - Quản trị',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90041',
                'expected_student_code'  => null,
                'full_name'              => 'Đỗ Hồng Nhi',
                'date_of_birth'          => '2008-11-05',
                'gender'                 => 'female',
                'cccd'                   => '064026266900',
                'phone'                  => '0989212676',
                'email'                  => 'nhidh081@gmail.com',
                'permanent_address'      => 'Số 26, Bến Tre',
                'major_code'             => 'XD',
                'major_name'             => 'Xây dựng',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90042',
                'expected_student_code'  => null,
                'full_name'              => 'Bùi Ngọc My',
                'date_of_birth'          => '2008-09-13',
                'gender'                 => 'female',
                'cccd'                   => '041181376420',
                'phone'                  => '0992874006',
                'email'                  => 'mybn08@gmail.com',
                'permanent_address'      => 'Số 59, Bình Dương',
                'major_code'             => 'TK',
                'major_name'             => 'Thiết kế',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90043',
                'expected_student_code'  => null,
                'full_name'              => 'Nguyễn Anh Bảo',
                'date_of_birth'          => '2008-06-14',
                'gender'                 => 'male',
                'cccd'                   => '019085320670',
                'phone'                  => '0985957578',
                'email'                  => 'baona08@gmail.com',
                'permanent_address'      => 'Số 21, Đồng Nai',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90044',
                'expected_student_code'  => null,
                'full_name'              => 'Hoàng Thị Phương',
                'date_of_birth'          => '2008-09-06',
                'gender'                 => 'female',
                'cccd'                   => '010157161130',
                'phone'                  => '0950151803',
                'email'                  => 'phuonght08@gmail.com',
                'permanent_address'      => 'Số 117, Lâm Đồng',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90045',
                'expected_student_code'  => null,
                'full_name'              => 'Nguyễn Hồng Linh',
                'date_of_birth'          => '2008-11-25',
                'gender'                 => 'female',
                'cccd'                   => '096098813690',
                'phone'                  => '0976669607',
                'email'                  => 'linhnh08@gmail.com',
                'permanent_address'      => 'Số 57, Kiên Giang',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90046',
                'expected_student_code'  => null,
                'full_name'              => 'Hoàng Thành Bảo',
                'date_of_birth'          => '2008-12-05',
                'gender'                 => 'male',
                'cccd'                   => '012158837900',
                'phone'                  => '0965767881',
                'email'                  => 'baoht08@gmail.com',
                'permanent_address'      => 'Số 94, Gia Lai',
                'major_code'             => 'QT',
                'major_name'             => 'Kinh tế - Quản trị',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90047',
                'expected_student_code'  => null,
                'full_name'              => 'Ngô Ngọc Phương',
                'date_of_birth'          => '2008-04-28',
                'gender'                 => 'female',
                'cccd'                   => '087184835420',
                'phone'                  => '0922120246',
                'email'                  => 'phuongnn08@gmail.com',
                'permanent_address'      => 'Số 32, Gia Lai',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90048',
                'expected_student_code'  => null,
                'full_name'              => 'Nguyễn Mỹ Trang',
                'date_of_birth'          => '2008-04-21',
                'gender'                 => 'female',
                'cccd'                   => '009147807760',
                'phone'                  => '0964800542',
                'email'                  => 'trangnm08@gmail.com',
                'permanent_address'      => 'Số 78, Bà Rịa - Vũng Tàu',
                'major_code'             => 'TH',
                'major_name'             => 'Công nghệ thông tin',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90049',
                'expected_student_code'  => null,
                'full_name'              => 'Lý Xuân Việt',
                'date_of_birth'          => '2008-08-20',
                'gender'                 => 'male',
                'cccd'                   => '053108238110',
                'phone'                  => '0959731689',
                'email'                  => 'vietlx08@gmail.com',
                'permanent_address'      => 'Số 93, Khánh Hòa',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
            [
                'admission_code'         => '01_TT_XTS_GBTT_90050',
                'expected_student_code'  => null,
                'full_name'              => 'Bùi Tuấn An',
                'date_of_birth'          => '2008-06-08',
                'gender'                 => 'male',
                'cccd'                   => '017019701270',
                'phone'                  => '0984384510',
                'email'                  => 'anbt08@gmail.com',
                'permanent_address'      => 'Số 85, Khánh Hòa',
                'major_code'             => 'CK',
                'major_name'             => 'Cơ khí',
                'course_year'            => '2026-2030',
                'school_year'            => '2026-2027',
                'status'                 => 'admitted',
            ],
        ];

        foreach ($importedCandidates as $data) {
            AdmissionCandidate::create($data);
        }
    }
}
